# Generated by Django 6.0.6 on 2026-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_candidate_linkedin_url_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Shortlisted', 'Shortlisted'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
